#!/bin/bash

# .bashrc
curl -fLo ~/.bashrc \
    https://raw.githubusercontent.com/TaoSama/Linux-rcs/master/bashrc
source ~/.bashrc

# .vimrc
curl -fLo ~/.vimrc \
    https://raw.githubusercontent.com/TaoSama/Linux-rcs/master/vimrc_server

source ~/.vimrc
