#!/bin/bash

# .bashrc
curl -fLo ~/.bashrc \
    https://raw.githubusercontent.com/TaoSama/Linux-rcs/master/bashrc
# cpp-headers for ICPC
curl --insecure -fLo  ~/.vim/templates/main.cpp --create-dirs \
    https://raw.githubusercontent.com/TaoSama/Linux-rcs/master/main.cpp

# .ycm_extra_conf.py
curl -fLo ~/.ycm_extra_conf.py \
    https://raw.githubusercontent.com/TaoSama/Linux-rcs/master/ycm_extra_conf.py

# plug.vim
curl --insecure -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# .vimrc
curl -fLo ~/.vimrc \
    https://raw.githubusercontent.com/TaoSama/Linux-rcs/master/vimrc

vim +PlugInstall
